2015-12-02 16:31:22,742 - Server start:
2015-12-02 22:49:13,941 - Server start:
2015-12-02 23:05:57,628 - 一个新连接接入[id: 0xaa5ef9b3, /192.168.1.4:64133 => /192.168.1.4:5000]
2015-12-02 23:06:03,992 - 报文长度出错
2015-12-02 23:06:14,046 - channel关闭[id: 0xaa5ef9b3, /192.168.1.4:64133 :> /192.168.1.4:5000]
2015-12-02 23:07:58,370 - 一个新连接接入[id: 0x2c3bec19, /192.168.1.4:64165 => /192.168.1.4:5000]
2015-12-02 23:08:03,686 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at java.lang.String.checkBounds(String.java:375)
	at java.lang.String.<init>(String.java:535)
	at com.hhjt.message.ConnectRequestMessage.decode(ConnectRequestMessage.java:17)
	at com.hhjt.message.ConnectRequestMessage.<init>(ConnectRequestMessage.java:12)
	at com.hhjt.message.MessageFactory.getMessage(MessageFactory.java:13)
	at com.hhjt.handlers.MessageDecodeHandler.decode(MessageDecodeHandler.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
	... 18 more
2015-12-02 23:08:13,680 - channel关闭[id: 0x2c3bec19, /192.168.1.4:64165 :> /192.168.1.4:5000]
2015-12-02 23:08:19,346 - 一个新连接接入[id: 0xb5c65ca1, /192.168.1.4:64166 => /192.168.1.4:5000]
2015-12-02 23:08:23,275 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at java.lang.String.checkBounds(String.java:375)
	at java.lang.String.<init>(String.java:535)
	at com.hhjt.message.ConnectRequestMessage.decode(ConnectRequestMessage.java:17)
	at com.hhjt.message.ConnectRequestMessage.<init>(ConnectRequestMessage.java:12)
	at com.hhjt.message.MessageFactory.getMessage(MessageFactory.java:13)
	at com.hhjt.handlers.MessageDecodeHandler.decode(MessageDecodeHandler.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
	... 18 more
2015-12-02 23:08:33,275 - channel关闭[id: 0xb5c65ca1, /192.168.1.4:64166 :> /192.168.1.4:5000]
2015-12-02 23:08:33,298 - 一个新连接接入[id: 0x611c3349, /192.168.1.4:64171 => /192.168.1.4:5000]
2015-12-02 23:08:35,833 - channel关闭[id: 0x611c3349, /192.168.1.4:64171 :> /192.168.1.4:5000]
2015-12-02 23:08:37,513 - 一个新连接接入[id: 0xcf3f0e85, /192.168.1.4:64172 => /192.168.1.4:5000]
2015-12-02 23:08:39,599 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 25
	at java.lang.String.checkBounds(String.java:375)
	at java.lang.String.<init>(String.java:535)
	at com.hhjt.message.ConnectRequestMessage.decode(ConnectRequestMessage.java:17)
	at com.hhjt.message.ConnectRequestMessage.<init>(ConnectRequestMessage.java:12)
	at com.hhjt.message.MessageFactory.getMessage(MessageFactory.java:13)
	at com.hhjt.handlers.MessageDecodeHandler.decode(MessageDecodeHandler.java:37)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:247)
	... 18 more
2015-12-02 23:08:49,600 - channel关闭[id: 0xcf3f0e85, /192.168.1.4:64172 :> /192.168.1.4:5000]
2015-12-02 23:09:36,497 - 一个新连接接入[id: 0x7e8c4f2f, /192.168.1.4:64176 => /192.168.1.4:5000]
2015-12-02 23:09:38,767 - do test!
2015-12-02 23:09:48,766 - channel关闭[id: 0x7e8c4f2f, /192.168.1.4:64176 :> /192.168.1.4:5000]
